### PR TITLE
Release 20.1.0

### LINKED ISSUE #2: Parsing result files
I think it would be great if we had a method/some methods for parsing the results data fetched from FEM-Design via `.bsc` batch files.

This could handle the information in the headers, instead of the user having to implement some custom method for parsing the tab (`\t`) separated values. Also dynamo can read **c**sv files but not **t**sv.

### LINKED ISSUE #15: CombItems from LoadCombination. Add exception.
Add exception if combItem is null.

https://github.com/strusoft/femdesign-api/blob/1ad8413edff7bbe5c29c6cfd6f72a37278c7306b/src/Calculate/Comb.cs#L117-L127

### LINKED ISSUE #67: Cont. CLT panel constructor component for GH
Case: 10109 

# Summary
Implement constructor components for CLT panels for Grasshopper.

## Continuous analytical model
An example of a continuous concrete panel can be found here:
https://github.com/strusoft/femdesign-api/blob/master/FemDesign.Grasshopper/Shells/ProfiledPlateDefine.cs

A public default constructor for timber panels is already available.
https://github.com/strusoft/femdesign-api/blob/dc4b3367274e617e3d082f23602c27a5983574d0/FemDesign.Core/Shells/Panel.cs#L529-L544

## CLT materials 
- TimberPanelLibraryType
- GlcDataType
- CltDataType

## To implement
- [x] MaterialDatabase reads CLT materials
- [ ] ~Get CLT materials from `GetMaterialByName()`~
- [x] Get CLT materials from `GetCltPanelLibraryTypeByName()`
- [x] Move MaterialByName method to MaterialDatabase class
- [x] TimberPlate.Define (GH component)
- [x] TimberPlateMaterialData.Define (GH component)
- [x] GetCltPanelLibraryTypeByName (GH component)
- [x] TimberFactors.Define (GH component)

## Tidy up
- [x] Create sample C# script
- [x] Create sample GH script
- [x] C# XML doc-strings
- [x] GH component descriptions

### LINKED ISSUE #73: Default value on node Design.define should be set to false
This will improve usability

### PR DESCRIPTION
**Pull request by xRadne**
### Resolved issues 
Fix #73 Default values on Design.define
Fix #67 CLT panels with grasshopper components
Fix #15 Missing `CombItems` exception
Fix #2 C# Methods for parsing Tabulated results to some classes (Most notably `PointSupportReaction` and `NodalDisplacement`). 

### Other features
- C# Constructor for class Model: `Model(string country, List<IStructureElement> elements = null, List<ILoadElement> loads = null, List<ISupportElement> supports = null)`
- Samples folder (`FemDesign.Samples`)

### CODE REVIEW

**Comment by xRadne** [comment]
The above comment can be used as Release notes once the PR has been closed.

**Comment by xRadne** [comment]
Only waiting for #9 (Model input) and #59 (Icons).

**Comment by andosca** [comment]
Looks really promising! 👷  @ c5a5eaa

**Comment by xRadne** [comment]
Tests successful:
✔ Dynamo script construct-deconstruct
✔ Grasshopper script construct-deconstruct
✔ Grasshopper script analysis

**Pull request merged**
