### PR TITLE
Update CmdListCen constructor with optional arguments

### LINKED ISSUE #8: CmdListGen options
Add options to set:

-Regional
-Fill all cells
-Headers

### PR DESCRIPTION
**Pull request by xRadne**
Fix #8 

Commit https://github.com/strusoft/femdesign-api/commit/4401dea05b4f9da970b8acccae00fdb8472faec2 updates CmdListCen constructor with optional arguments. 

This won't affect Grasshopper or Dynamo.

### CODE REVIEW

**Review by andosca — COMMENTED** [review]
I think we should set bool-to-int conversion at property level so that the user does not have to consider int.

See example: 

https://github.com/strusoft/femdesign-api/blob/8024e8e58e444421dd288a18c10b906978995670/src/Calculate/Analysis.cs#L41-L54

**Comment by xRadne** [comment]
Updated getters and setters with bool-to-int conversion

**Review by andosca — COMMENTED** [review]
Nice!

**Comment by xRadne** [comment]
@andosca FYI
I made a test with 
```xml
  <cmdlistgen command="$ MODULECOM LISTGEN" bscfile="..." outfile="..." fillcells="true" headers="true" regional="false"/>
  <cmdlistgen command="$ MODULECOM LISTGEN" bscfile="..." outfile="..." fillcells="1" headers="1" regional="0"/>
```
Both of these works fine with FEM-Design. So it should not be needed to have serializable int fields:
```c#
[XmlAttribute("calcCStage")] 
public int _calcCStage; // bool as int 
```
but this should serialize to `calcCStage="true"` and should thus be sufficient:
```c#
[XmlAttribute("calcCStage")] 
 public bool CalcCStage;
```

**Comment by andosca** [comment]
@xRadne 

Nice! Then we can skip using int for fdscript.

**Pull request merged**
