### PR TITLE
Load groups & Load combiner

### PR DESCRIPTION
**Pull request by GabrielEdefors**
Hej, jag vill bara börja med att tacka för att ni har gjort källkoden till API:n tillgänglig! Jag har lagt till några komponenter för att kombinera lastfall på likande sätt som för lastgrupper i FEM design. I dagsläget skapas kombinationerna i en separat klass och skickas på samma sätt som tidigare till modellkomponenten (lastgrupperna skickas alltså inte till FEM Design).  Det återstår en del verifiering innan jag är 100 på att allt fungerar som det ska, men jag tänkte jag gör en draft pull request för att kolla om ni eventuellt är intresserade och i så fall om ni har några förslag på förbättringar.

### CODE REVIEW

**Comment by andosca** [comment]
@GabrielEdefors Jag tar och tittar på detta så fort som jag kan :)

**Comment by xRadne** [comment]
Otroligt bra jobbat Gabriel! Detta ska vi se till att det kommer med i API:et! 🚀

**Comment by xRadne** [comment]
I'm starting a list of what needs to be done. Please fill in anything missing.
## To be done:
- [x] Naming of components
- [ ] Add a class for `load_group_table` on `Model.Entities.Loads.LoadGroupTables` (instead of `DummyXmlObject`)


### Class `LoadGroupTables` should look something like this:
```xml
<load_group_table last_change="2021-11-09T08:26:22.000" action="added" simple_combination_method="false">
  <group name="LG-1" guid="4e32b65d-07f6-4836-a1af-4c140fdf0e3e">
    <permanent standard_favourable="0.9" standard_unfavourable="1.35" xi="0.89" accidental_favourable="1" accidental_unfavourable="1">
      <load_case guid="4df75738-772a-4e83-af4d-eb886cd8a5fa"></load_case>
      <subgroup name="SG-1">
        <load_case guid="53c89f09-4c18-44ce-bc9c-7273631a82ec"></load_case>
        <load_case guid="671d72e0-672e-4ee4-9af4-947ba66644bd"></load_case>
      </subgroup>
    </permanent>
  </group>
</load_group_table>
```

**Comment by GabrielEdefors** [comment]
Tack för feedbacken! Ska kika lite på LoadGroupTables inom kort :) Brukar ni förresten göra unit testing och liknande för att säkerhetställa att allt funkar som det ska?

**Comment by xRadne** [comment]
> Tack för feedbacken! Ska kika lite på LoadGroupTables inom kort :) 

Låter bra!

> Brukar ni förresten göra unit testing och liknande för att säkerhetställa att allt funkar som det ska?

Än så länge nej. Men en grund för unit tests av C#/Core metoder kommer i nästa release 20.2.0 (#83). När den är merged kanske vi väljer att skapa unit tests för ny kod. Men isåfall kan jag ta hand om det.

**Comment by GabrielEdefors** [comment]
- [x]  Added load_group_table
- [ ]  Add deconstruct for load groups

**Comment by xRadne** [comment]
I see that you have made great progress @GabrielEdefors !
Do you need help with anything? 
And do you hava an example script (C#/Grasshopper?) that you have been testing with while developing? If so, you are very welcome to add that to the `FemDesign.Samples` folder as well 😄

**Comment by GabrielEdefors** [comment]
> I see that you have made great progress @GabrielEdefors ! Do you need help with anything? And do you hava an example script (C#/Grasshopper?) that you have been testing with while developing? If so, you are very welcome to add that to the `FemDesign.Samples` folder as well 😄

Hi! I think that I succesfully have implemented the load group table and it seems that the xml serializer is generating a correct struxml file containg the load groups. I do however have some difficulties creating serializable child classes that inherit properties (I basically want to avoid creating a whole class for each type of load group), I would very much appriciate some help with this. I basically dont want to duplicate the code that is common among these classes

        <xs:element name="accidental"  type="accidental_load_group" />
        <xs:element name="permanent"   type="permanent_load_group"  />
        <xs:element name="seismic"     type="seismic_load_group"    />
        <xs:element name="stress"      type="stress_load_group"     />
        <xs:element name="temporary"   type="temporary_load_group"  />

do you have any suggestions how to do this, or do you think it is preferable to have seperate classes with no inheritance?

 I also think that the code is somewhat complicated since I have two kinds of load group classes, one that is serializable and one that is not. To avoid casting between them I will try to stick to only one class. Once that is done it should be easy to implement a deconstruct component for the load groups as well.

**Comment by xRadne** [comment]
I created a sample script to test your implementation and I think it is great! 🚀


> do you have any suggestions how to do this, or do you think it is preferable to have seperate classes with no inheritance?
> 
> I also think that the code is somewhat complicated since I have two kinds of load group classes, one that is serializable and one that is not. To avoid casting between them I will try to stick to only one class. Once that is done it should be easy to implement a deconstruct component for the load groups as well.

I'm not sure what is the best solution here, so please feel free to do what you feel like! But I think it might be good to have One class for each LoadGroup (since they have different properties), but then also have a base class (`LoadGroupBase`) that they all inherit the shared properties (`ModelLoadCase`, `ELoadGroupRelationship` and maybe a `Relations` property). Have a look at [LoadBase](https://github.com/strusoft/femdesign-api/blob/master/FemDesign.Core/Loads/LoadBase.cs) for example. 

It will be a bit tricky to deconstruct the LoadGroups, yes. But if they are different C# classes then the Grasshopper deconstructor can check the type and output null for the irrelevant properties.

**Comment by GabrielEdefors** [comment]
> I created a sample script to test your implementation and I think it is great! 🚀

Thanks @xRadne! 

> I'm not sure what is the best solution here, so please feel free to do what you feel like! But I think it might be good to have One class for each LoadGroup (since they have different properties), but then also have a base class (`LoadGroupBase`) that they all inherit the shared properties (`ModelLoadCase`, `ELoadGroupRelationship` and maybe a `Relations` property). Have a look at [LoadBase](https://github.com/strusoft/femdesign-api/blob/master/FemDesign.Core/Loads/LoadBase.cs) for example.
> It will be a bit tricky to deconstruct the LoadGroups, yes. But if they are different C# classes then the Grasshopper deconstructor can check the type and output null for the irrelevant properties.

Hi again! I think I have resolved these issues and managed to get rid of one load group class. I finally begin to feel quite satisfied with the load group and load group combination features. It remains to do some more verifications and testing before I feel confident that it works as expected though.

**Comment by xRadne** [comment]
Amazing! Will have a look next year! 🎄

**Comment by xRadne** [comment]
I merged the changes to the current master branch into this PR. The biggest change of interest for you is that we have introduced more enum types (such as `LoadCaseType.DeadLoad` and `LoadCaseDuration.Permanent` etc.). I have updated the sample and tests according to these changes. 😊

Let me know once you want the PR to be properly reviewed 🧐

**Comment by GabrielEdefors** [comment]
> Let me know once you want the PR to be properly reviewed 🧐

Perfect, thanks! I think the code is ready to be reviewed :)

**Comment by GabrielEdefors** [comment]
- Fix problem that loadGroupTables cant be empty []

- Fix so the user can create own load categories []

**Comment by xRadne** [comment]
### 🏁 Review status:
Checked and approved:
- [ ] All changed files looks okay.
- [ ] Able to merge with master
- [ ] Code does not break old grasshopper scripts
- [x] Code does not break old dynamo scripts
- [x] Code does not break old C# Samples
- [x] Added unit tests are successful 
- [ ] Intuitive to use for the user. Following the structure of FEM-Design if possible and simple if possible. 
- [ ] Load Groups works as expected. Does what it should and nothing else.

**Comment by xRadne** [comment]
> * [ ]  Fix problem that loadGroupTables cant be empty

@GabrielEdefors Could you please confirm that this have been fixed with the following code:

https://github.com/GabrielEdefors/femdesign-api/blob/39639201dab9d3e3d97bf7e7425f253bf462f711/FemDesign.Core/Model/Model.cs#L1376-L1399

**Review by xRadne — APPROVED** [review]
The reviewed files are all good! 🚀

**Pull request merged**
