### PR TITLE
Footfall analysis

### PR DESCRIPTION
**Pull request by xRadne**
Not ready to be merged. 

See https://github.com/strusoft/femdesign-api/issues/39#issue-890151964 for discussion.

### CODE REVIEW

**Comment by xRadne** [comment]
@andosca This PR is ready to be merged. Do you want to have a look at it before we merge? If not I think it is safe to merge since I have tested it in C#, Dynamo and Grasshopper.

**Comment by andosca** [comment]
Footfall analysis needs to be implemented here also:

https://github.com/strusoft/femdesign-api/blob/%2339-Footfall-analysis/FemDesign.Core/Loads/GenericLoadObject.cs

**Comment by xRadne** [comment]
By using `ILoadElement` instead of `GenericLoadObject` any load object can be used in `Model.CreateModel` and `Model.AddEntities`. 
https://github.com/strusoft/femdesign-api/blob/bbbd683f0b90d75ce2a865c050f32be28af7cbc6/FemDesign.Grasshopper/Model/ModelCreate.cs#L96

https://github.com/strusoft/femdesign-api/blob/bbbd683f0b90d75ce2a865c050f32be28af7cbc6/FemDesign.Grasshopper/Model/ModelCreate.cs#L133

Then for `Model.ModelDeconstruct` `GetLoads()` also get Footfall loads:  
I have checked this in Dynamo but not in Grasshopper.

**Comment by xRadne** [comment]
I have not implemented `FootfallDeconstruct` Grasshopper node and not a Dynamo static method. 

Should this be added?

**Pull request merged**
