### PR TITLE
General load combination generation

### PR DESCRIPTION
**Pull request by Boohman**
Adds:
- A load combination component in Grasshopper Utils that combines load cases based on a national annex
- An enum to the Core for keeping track of national annexes
- A class to the Core for generating combinations based on a national annex

### CODE REVIEW

**Comment by Marco-Pellegrino** [comment]
Hi @Boohman !
We will review the pull-request and come back to you ASAP. Some time before the end of next week.

**Comment by andosca** [comment]
@Marco-Pellegrino Before merging we should refactor some code #656

**Comment by andosca** [comment]
#660

**Comment by Marco-Pellegrino** [comment]
@Boohman 
Thanks for your work and commits.

After a minor review, we have decided to merge your pull request.
You can see what it has changed in the commit history ( if statement logic replaced with a switch case) and move part of the code to a different folder and namespace called `Utils`

**Comment by Marco-Pellegrino** [comment]
we are closing the pull-request as it has been merged in the Development branch and not master.
I was not currently aware that it was possible to change the base branch.

**Pull request closed without merging**
