### PR TITLE
Parametric study of boundary condition for a bridge

### PR DESCRIPTION
**Pull request by ShahoRuhani**

### CODE REVIEW

**Comment by ShahoRuhani** [comment]
[Bridge Model.zip](https://github.com/strusoft/femdesign-api/files/8416806/Bridge.Model.zip)

**Comment by andosca** [comment]
Can you add the necessary example files to FemDesign.Samples/C#/ExampleModels/`YourFolder` and change the absolute paths to relative paths so that the sample works out of the box. 

Please name `YourFolder` such that there is a relation between the name of the sample and the folder.

**Review by xRadne — APPROVED** [review]
Tested the example and made some cleanup among the examples. This can now be merged @andosca

**Comment by andosca** [comment]
@xRadne  Can you resolve conflicts? Looks like there are some conflicts between changes by @ShahoRuhani  and @samnyb

**Comment by xRadne** [comment]
> @xRadne Can you resolve conflicts? Looks like there are some conflicts between changes by @ShahoRuhani and @samnyb

Resolved! :)

**Pull request merged**
