### PR TITLE
Release 20.2.0

### PR DESCRIPTION
**Pull request by xRadne**
### Changes
- #11
- Created a Python sample script #33 #34
- #50
- #78
- #79
- #82 
- #86 
- #88
- #94

### Bugs fixed
- #69 
- #85 
- 🚑 Footfall loads now use Regions instead of List<Contour>. Following service release 20.00.003. See commit 19c7557ec488c5b1068079da79f04c7087af9858

### Extra
- Updated and added a few samples for Grasshopper, C# and Python

### Before merge
- [x] Add icons
- [x] Update version number to 20.2.0
- [x] Write Release notes (Use the above)

### CODE REVIEW

**Review by andosca — CHANGES_REQUESTED** [review]
Typo `regidity` - should be `rigidity`

**Comment by xRadne** [comment]
No breaking changes in grasshopper as far as I can see now. 
Tested against our internal test scripts:
image

**Comment by xRadne** [comment]
Updated and ran global tests. Found 2 new potential bugs:

- [ ] 4b8c71dc-9a49-41a2-ab1c-273cfd6da0ce | Warning: this cover is done, but many supporting structures are missing or inadequate!
- [ ] 50aae4e4-9aec-483d-924b-42e202aba792 | Error:   Can't create punching reinforcement, because improper material!

The second issue only appeared at `debug3.struxml` and `debug4.struxml`

**Comment by xRadne** [comment]
Ready to merge IMO :godmode:

**Comment by xRadne** [comment]
@andosca Are you uploading the latest version to Food4Rhino as well? (And please check if materials, sections and icons are included 😉)

**Pull request merged**
